version: '3.8'

services:
  # Backend - API do Supervisor (Produção)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: supervisor-backend-prod
    ports:
      - "3000:3000"
    volumes:
      - supervisor-data:/app/data
      - supervisor-database:/app/database
    environment:
      - NODE_ENV=production
    restart: always
    privileged: true
    networks:
      - supervisor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend - Interface Web (Produção)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: supervisor-frontend-prod
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3000
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    networks:
      - supervisor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx - Proxy Reverso (Opcional)
  nginx:
    image: nginx:alpine
    container_name: supervisor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - supervisor-network

networks:
  supervisor-network:
    driver: bridge

volumes:
  supervisor-data:
    driver: local
  supervisor-database:
    driver: local





