version: '3.8'

services:
  # Backend - API do Supervisor
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: supervisor-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/database:/app/database
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    privileged: true
    networks:
      - supervisor-network

  # Frontend - Interface Web
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: supervisor-frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - supervisor-network

networks:
  supervisor-network:
    driver: bridge

volumes:
  supervisor-data:
    driver: local

